#
# Edited Sera - OnePage Jekyll Template
# Configuration File
#

# Information for compile
exclude: ["node_modules", "gulpfile.js", "package.json", "README.md"]

#redirect url




#######################################################
#######################################################
###############   HEADER INFORMATIONS   ###############
#######################################################
#######################################################

# This is your site title
title: I fagerlinds tid
# Website language
lang: en-US
# Header Title
header-title: I Fagerlinds tid
# Header Tagline
headter-tagline: I Fagerlinds tid

contact-title: Boka Fagerlinds Testamente

####################################
######   CTA Header Buttons   ######
####################################

# Focus Buttons
header-focus-button:
  title: Boka!
  url: '#boking'

# Secondary Buttons
header-secondary-button:
  title: Jag vill veta mer...
  url: '#about'

#
# If your website is placed in a separate folder on your server please modify
# this with your folder name, by default is empty.
# Example: Sera Demo is hosted on projects.gleesik.ro/sera-onepage
# If I compile Sera Template and I put in /sera-onepage without modifing baseurl
# than scripts can't be loaded corectly.
# For this example my site url is: projects.gleesik.ro (This can be just www.example.com)
# My folder for Demo Website is: /sera-onepage so baseurl: /sera-onepage
#
baseurl: 

#
# This is your email adress, contact from send here all emails from contact section
# IMPORTANT: you can modify contact form from this static template, but now works contact form works with a free external server
# To configure this contact form, first please send a fictive email afeter you enter below your email and verify that :)
#
email: info@fagerlindstid.se

# Offer Banner Link
# Default link is a link to all Sera OnePage products
banner-link: '#boking'

####################################
######  Global Social Links   ######
####################################

facebook: 'https://www.facebook.com/FagerlindsTid/'
tripadvisor: 'https://www.tripadvisor.se/Attraction_Review-g189861-d12539359-Reviews-Orebro_Escape_Room-Orebro_Orebro_County.html'
twitter: '#'
google-plus: '#'
vimeo: '#'
youtube: '#'
pinterest: '#'

#########################
######   Widgets   ######
#########################

#
# About Blog Author Widget
#
about-widget:
  author-avatar: avatar-02.jpg
  author-name: Joche
  author-tagline: Lord of mystery
  author-info: Cum sociis que penatibus et magnis dis parturient montes lorem, nascetur ridiculus mus. Donec quam felis, ultricies nec.
  author-social-links:
    youtube: '#'
    pinterest: '#'
    facebook: '#'
    twitter: '#'
    google-plus: '#'

# Google Map JS api
# This is my api for this template
key-api: AIzaSyAGaPq4LFgEpw6fnIMeDZsYwfUKTuoPitc
map-text: Makeriet
map-text-location: Centrum, Örebro
map-lat: 59.2719217
map-lng: 15.2160504

# Enter your Mailchimp User ID and Campaign ID
# @TODO: Add in a link for where to find these
mailchimp:
  user-id: REPLACEME
  list-id: REPLACEME



#####################################
#############   About   #############
#####################################
about-title: VÄLKOMMEN TILL FAGERLINDS TID
about-description: "Ta del av ett spännande äventyr fyllt av mysterier, gåtor och hemliga uppdrag där ni har huvudrollen. <br><br> Utmana er själva, arbeta tillsammans som ett lag och tävla mot klockan. <br><br> I Makeriets anrika lokaler, som återger känslan av ett Örebro i början av 1900 talet, finner ni en annorlunda och nyskapande sorts underhållning som passar utmärkt för vännerna, familjen eller kollegorna."

#####################################
#############   About Escape Room  #############
#####################################


about-escape-title: VAD ÄR ESCAPE ROOM?
about-escape-description: Escape Room är en lagbaserad utmaning för 2 till 6 spelare. Gruppen blir ”inlåst” i ett rum där det primära målet är att ta sig ut. <br> <br> Speltiden är 60 minuter och med hjälp av ledtrådar dolda runt omkring i rummet och dess inredning ska gruppen lösa en serie av gåtor, kluriga pussel och knäcka koder för att ta sig vidare i spelet. <br> <br> Escape Room är en spännande och rolig underhållning som passar de flesta och är perfekt utformad för möhippan, svensexan eller företagets kickoff / teambuilding. För större grupper kontakta oss så hjälper vi er att skräddarsy den perfekta upplevelsen för just er.


#####################################
#############   Snabbfakta #############
#####################################


snabbfakta-title: SNABBFAKTA
snabbfakta-description:




#####################################
#############   FAQ Escape Room  #############
#####################################


faq-title: FAQ
faq-description: 





#####################################
#############   Hitta Escape Room  #############
#####################################

hitta-title: Hitta Hit
hitta-description: Kungsgatan 3, Örebro <br> <br> Vi delar lokaler med restaurangen Makeriet och ni finner Fagerlinds Tid på andra våning. Entré via någon av Makeriets ingångar och i avdelningen Brasseriet, glashuset, finner ni trappan upp till oss. Tveka inte att fråga någon av Makeriets personal, de hjälper er så gärna att hitta rätt.




# "Vilka öppettider har ni?
# Vårt tidigaste rum går att boka klockan 10:00 och de senaste 22:00.
# Vi har totalt 10 möjliga speltillfällen per dygn. All bokning sker via vår hemsida.
# Restaurangens öppettider hittar ni här.

# Vad kostar ett spel?
# Det beror på storleken på er grupp.
# 2 personer – 350:- per person
# 3 personer – 295:- per person
# 4 personer – 275:- per person
# 5 personer – 250:- per person
# 6 personer – 225:- per person

# Vart ligger Örebro Escape Room?
# Vår adress är Kungsgatan 3 i Örebro,
# vi delar lokal med restaurangen Makeriet.

# Behöver jag vara jättesmart, stark, smidig och duktig på matematik för att spela?
# Nej. Det handlar om att kunna arbeta som lag och problemlösning. Det är inga svåra uträkningar som behövs göras eller IQ-tester. Inga pussel kräver att du kan klättra eller lyfta tungt eller dyl.

# Blir vi inlåsta på riktigt?
# Nej, dörren ut är alltid olåst och ni kan välja att lämna när ni vill.
# När ska vi vara på plats och vad händer om vi kommer sent?
# Var på plats 10-15 minuter innan bokad tid för genomgång av regler och rummet. Om ni anländer sent dras det på er speltid.

# Kommer vi tävla mot varandra?
# Nej, en stor del av nöjet med Escape Rooms är att man sammarbetar och jobbar som ett lag. Däremot kan ni komma i två lag och tävla mot varandra om vilka som klarar av ett rum på så kort tid så möjligt.

# Vad händer om vi inte löser rummet i tid?
# Efter 60 minuter är spelet slut, är ni fortfarande kvar i rummet släpps ni ut.

# Får vi ta med alkohol?
# Nej, på grund av alkoholtillståndet restaurangen har är det inte tillåtet att dricka medhavd alkohol. Men Makeriets bar går fint att besöka både före och efter ni spelat.

# Har ni någon åldergräns?
# För att spela våra rum ska du vara minst 18 år, eller 16 i vuxet sällskap.

# Hur betalar vi?
# Betalning sket på plats innan spelet börjar, vi tar bara emot kortbetalning.

# Går det att köpa presentkort hos er?
# Absolut! Du köper presentkortet på plats hos oss och väljer själv värdet.

# Får vi filma och fotografera i rummet när vi spelar?
# Nej. Vi vill behålla mystiken för andra som vill spela hos oss.

# Läs mer på Wikipedia.
# https://en.wikipedia.org/wiki/Escape_room"




#####################################
#############  Features  ############
#####################################
features-title: Rum
features-description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean at tincidunt sem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante.

#
# Features
#
features:

# Feature
- title: Clean & Unique Design
  description: Maecenas sed laoreet urna. Praesent eget tristique tortor. Suspendisse consequat sed turpis in mattis.
  icon: pe-7s-vector

# Feature
- title: Professional Support
  description: Maecenas sed laoreet urna. Praesent eget tristique tortor. Suspendisse consequat sed turpis in mattis.
  icon: pe-7s-help2

# Feature
- title: Pixel Perfect
  description: Maecenas sed laoreet urna. Praesent eget tristique tortor. Suspendisse consequat sed turpis in mattis.
  icon: pe-7s-airplay



#####################################
##########  Core Features  ##########
#####################################
core-title: Spel 1 - Fagerlinds Testamente
core-description: Det är den 19e mars 1924, och den fruktansvärda nyheten att Johan Fagerlind nyligen omkommit i en brand i sin skofabrik har nått hans tidigare kollega grosshandlare C.A. Carlsson. Fagerlind var skyldig Carlsson stora summor pengar och därför har grosshandlaren nu anställt er för att bryta er in i Johan Fagerlinds kontor och där leta upp hans kassaskåp och tömma det. Men skynda er på för stadens konstapel är också på väg dit och blir ni gripna är utebliven betalning för jobbet ert minsta problem.

core-title-2: Spel 2 - Major Cederströms vinkällare.
core-description-2: Öppnar snart



#####################################
#############   Footer   ############
#####################################
footer-description: Fagerlinds tid är skapad av Joche Inc.
footer-copyright-text: Daniel Sundén 
footer-copyright-url: http://daniel.sunden.se
footer-copyright-year: 2017
