#
# Edited Sera - OnePage Jekyll Template
# Configuration File
#

# Information for compile
exclude: ["node_modules", "gulpfile.js", "package.json", "README.md"]

#######################################################
#######################################################
###############   HEADER INFORMATIONS   ###############
#######################################################
#######################################################

# This is your site title
title: I fagerlinds tid
# Website language
lang: en-US
# Header Title
header-title: I Fagerlinds tid
# Header Tagline
headter-tagline: Örebro Escape Room

####################################
######   CTA Header Buttons   ######
####################################

# Focus Buttons
header-focus-button:
  title: Boka!
  url: '#boking'

# Secondary Buttons
header-secondary-button:
  title: Jag vill veta mer...
  url: '#about'

#
# If your website is placed in a separate folder on your server please modify
# this with your folder name, by default is empty.
# Example: Sera Demo is hosted on projects.gleesik.ro/sera-onepage
# If I compile Sera Template and I put in /sera-onepage without modifing baseurl
# than scripts can't be loaded corectly.
# For this example my site url is: projects.gleesik.ro (This can be just www.example.com)
# My folder for Demo Website is: /sera-onepage so baseurl: /sera-onepage
#
baseurl: 

#
# This is your email adress, contact from send here all emails from contact section
# IMPORTANT: you can modify contact form from this static template, but now works contact form works with a free external server
# To configure this contact form, first please send a fictive email afeter you enter below your email and verify that :)
#
email: info@örebroescaperoom.com

# Offer Banner Link
# Default link is a link to all Sera OnePage products
banner-link: '#boking'

####################################
######  Global Social Links   ######
####################################
youtube: '#'
pinterest: '#'
facebook: '#'
twitter: '#'
google-plus: '#'
vimeo: '#'

#########################
######   Widgets   ######
#########################

#
# About Blog Author Widget
#
about-widget:
  author-avatar: avatar-02.jpg
  author-name: Joche
  author-tagline: Lord of mystery
  author-info: Cum sociis que penatibus et magnis dis parturient montes lorem, nascetur ridiculus mus. Donec quam felis, ultricies nec.
  author-social-links:
    youtube: '#'
    pinterest: '#'
    facebook: '#'
    twitter: '#'
    google-plus: '#'

# Google Map JS api
# This is my api for this template
key-api: AIzaSyAGaPq4LFgEpw6fnIMeDZsYwfUKTuoPitc
map-text: Örebro Escape Room 
map-text-location: Centrum, Örebro
map-lat: 59.2719217
map-lng: 15.2160504

# Enter your Mailchimp User ID and Campaign ID
# @TODO: Add in a link for where to find these
mailchimp:
  user-id: REPLACEME
  list-id: REPLACEME



#####################################
#############   About   #############
#####################################
about-title: Välkommen till Örebro Escape Room
about-description: Välkomna till Makeriet och Örebro Escape Games. Ta del av ett spännande spel fyllt av mysterier, gåtor och hemliga uppdrag där ni har huvudrollen. Utmana er själva, arbeta tillsammans som ett lag och tävla mot klockan. I Makeriets anrika lokaler, som återger känslan av ett Örebro i början av 1900-talet, finner ni en annorlunda och nyskapande sorts underhållning som passar utmärkt för vännerna, familjen eller kollegorna.


#####################################
#############   About Escape Room  #############
#####################################


about-escape-title: VAD ÄR ESCAPE ROOM?
about-escape-description: Escape Room är en lagbaserad utmaning för 2 till 6 spelare. Gruppen blir ”inlåst” i ett rum där det primära målet är att ta sig ut. <br> <br> Speltiden är 60 minuter och med hjälp av ledtrådar dolda runt omkring i rummet och dess inredning ska gruppen lösa en serie av gåtor, kluriga pussel och knäcka koder för att ta sig vidare i spelet. <br> <br> Escape Room är en spännande och rolig underhållning som passar de flesta och är perfekt utformad för möhippan, svensexan eller företagets kickoff / teambuilding. För större grupper kontakta oss så hjälper vi er att skräddarsy den perfekta upplevelsen för just er.



#####################################
#############  Features  ############
#####################################
features-title: Rum
features-description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean at tincidunt sem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante.

#
# Features
#
features:

# Feature
- title: Clean & Unique Design
  description: Maecenas sed laoreet urna. Praesent eget tristique tortor. Suspendisse consequat sed turpis in mattis.
  icon: pe-7s-vector

# Feature
- title: Professional Support
  description: Maecenas sed laoreet urna. Praesent eget tristique tortor. Suspendisse consequat sed turpis in mattis.
  icon: pe-7s-help2

# Feature
- title: Pixel Perfect
  description: Maecenas sed laoreet urna. Praesent eget tristique tortor. Suspendisse consequat sed turpis in mattis.
  icon: pe-7s-airplay



#####################################
##########  Core Features  ##########
#####################################
core-title: Rum 1 - Fabrikant Johan Fagerlind
core-description: Det är den 19e mars,1924, och den fruktansvärda nyheten att Johan Fagerlind nyligen omkommit i en brand i sin skofabrik har nått hans tidigare kollega grosshandlare C.A. Carlsson. Fagerlind var skyldig Carlsson stora summor pengar och därför har grosshandlaren nu anställt er för att bryta er in i Johan Fagerlinds kontor och där leta upp hans kassaskåp och tömma det. Men skynda er på för stadens konstapel är också på väg dit och blir ni gripna är utebliven betalning för jobbet ert minsta problem.

core-title-2: Rum 2 - Major Cederströms vinkällare.
core-description-2: Spionage för Sovjetunionen. I3 örebro Livregementets grenadjärer. Första världskriget 1914 – 1918. Året är 1917 och Europa står i lågor medan världskriget rasar på. <br> <br><br><br>Kommer snart...




#####################################
#############   Footer   ############
#####################################
footer-description: I Fagerlinds tid är skapad av Joche Inc.
footer-copyright-text: Joachim Niklasson
footer-copyright-url: http://daniel.sunden.se
footer-copyright-year: 2017
