#
# Sera - OnePage Jekyll Template
# Configuration File
#

# Information for compile
exclude: ["node_modules", "gulpfile.js", "package.json", "README.md"]

#######################################################
#######################################################
###############   HEADER INFORMATIONS   ###############
#######################################################
#######################################################

# This is your site title
title: I fagerlinds tid
# Website language
lang: en-US
# Header Title
header-title: I fagerlinds tid
# Header Tagline
headter-tagline: Örebro Escape Room

####################################
######   CTA Header Buttons   ######
####################################

# Focus Buttons
header-focus-button:
  title: Boka!
  url: '#boking'

# Secondary Buttons
header-secondary-button:
  title: Jag vill veta mer...
  url: '#about'

#
# If your website is placed in a separate folder on your server please modify
# this with your folder name, by default is empty.
# Example: Sera Demo is hosted on projects.gleesik.ro/sera-onepage
# If I compile Sera Template and I put in /sera-onepage without modifing baseurl
# than scripts can't be loaded corectly.
# For this example my site url is: projects.gleesik.ro (This can be just www.example.com)
# My folder for Demo Website is: /sera-onepage so baseurl: /sera-onepage
#
baseurl: 

#
# This is your email adress, contact from send here all emails from contact section
# IMPORTANT: you can modify contact form from this static template, but now works contact form works with a free external server
# To configure this contact form, first please send a fictive email afeter you enter below your email and verify that :)
#
email: info@örebroescaperoom.com

# Offer Banner Link
# Default link is a link to all Sera OnePage products
banner-link: '#boking'

####################################
######  Global Social Links   ######
####################################
youtube: '#'
pinterest: '#'
facebook: '#'
twitter: '#'
google-plus: '#'
vimeo: '#'

#########################
######   Widgets   ######
#########################

#
# About Blog Author Widget
#
about-widget:
  author-avatar: avatar-02.jpg
  author-name: Joche
  author-tagline: Lord of mystery
  author-info: Cum sociis que penatibus et magnis dis parturient montes lorem, nascetur ridiculus mus. Donec quam felis, ultricies nec.
  author-social-links:
    youtube: '#'
    pinterest: '#'
    facebook: '#'
    twitter: '#'
    google-plus: '#'

# Google Map JS api
# This is my api for this template
key-api: AIzaSyDbnxVZQannH0GF4gtnnBFPiP9ofm2WqGs
map-text: Örebro Escape Room 
map-text-location: Centrum, Örebro
map-lat: 59.2719217
map-lng: 15.2160504

# Enter your Mailchimp User ID and Campaign ID
# @TODO: Add in a link for where to find these
mailchimp:
  user-id: REPLACEME
  list-id: REPLACEME

####
#
# Hi you now use Sera - OnePage Jekyll Template created by Gleesik™
#
# Below are each section from the website in order from top to bottom
# @TODO Edit each sections with your real information and each section from Sera will autocomplete with your information
#
####

#####################################
#############   About   #############
#####################################
about-title: Välkommen till Örebro Escape Room
about-description: Välkomna till Makeriet och Örebro Escape Games. Ta del av ett spännande spel fyllt av mysterier, gåtor och hemliga uppdrag där ni har huvudrollen. Utmana er själva, arbeta tillsammans som ett lag och tävla mot klockan. I Makeriets anrika lokaler, som återger känslan av ett Örebro i början av 1900-talet, finner ni en annorlunda och nyskapande sorts underhållning som passar utmärkt för vännerna, familjen eller kollegorna.


#####################################
#############   About Escape Room  #############
#####################################


about-escape-title: VAD ÄR ESCAPE ROOM?
about-escape-description: Escape Room är en lagbaserad utmaning för 2 till 6 spelare. Gruppen blir ”inlåst” i ett rum där det primära målet är att ta sig ut. <br> <br> Speltiden är 60 minuter och med hjälp av ledtrådar dolda runt omkring i rummet och dess inredning ska gruppen lösa en serie av gåtor, kluriga pussel och knäcka koder för att ta sig vidare i spelet. <br> <br> Escape Room är en spännande och rolig underhållning som passar de flesta och är perfekt utformad för möhippan, svensexan eller företagets kickoff / teambuilding. För större grupper kontakta oss så hjälper vi er att skräddarsy den perfekta upplevelsen för just er.



#####################################
############  Portfolio  ############
#####################################
# portfolio-title: Våra rum
# portfolio-description: Maecenas tempus nec mi et placerat. Duis at odio vitae ex gravida volutpat. Nulla finibus aliquet diam ut eleifend. Mauris consequat interdum quam. Mauris dui sapien, efficitur et cursus id, molestie fringilla turpis.

# #
# # Portfolio Grid
# #
# portfolio-categories: [Websites, Logo, Graphic Design, Development, Video, Photography]
# portfolio:

# # Portfolio Item
# - title: Fabrikant Johan Fagerlind
#   categories: ett kassaskåp 1924...
#   image: img-01.jpg
#   url: '#'

# # Portfolio Item
# - title: Major Cederströms vinkällare
#   categories: första världskriget 1914
#   image: img-02.jpg
#   url: '#'

# # Portfolio Item
# - title: S<span class="thin">era</span> Style
#   categories: [Graphic Design, Logo, Photography]
#   image: img-03.jpg
#   url: '#'

# # Portfolio Item
# - title: S<span class="thin">era</span> Style
#   categories: [Websites, Video, Photography]
#   image: img-04.jpg
#   url: '#'

# # Portfolio Item
# - title: S<span class="thin">era</span> Style
#   categories: [Development, Logo]
#   image: img-05.jpg
#   url: '#'

# # Portfolio Item
# - title: S<span class="thin">era</span> Style
#   categories: [Development, Video]
#   image: img-06.jpg
#   url: '#'

# # Portfolio Item
# - title: S<span class="thin">era</span> Style
#   categories: [Websites, Graphic Design]
#   image: img-07.jpg
#   url: '#'

# # Portfolio Item
# - title: S<span class="thin">era</span> Style
#   categories: [Websites , Video]
#   image: img-08.jpg
#   url: '#'

# # Portfolio Item
# - title: S<span class="thin">era</span> Style
#   categories: [Photography, Logo]
#   image: img-09.jpg
#   url: '#'


#####################################
#############  Features  ############
#####################################
features-title: Rum
features-description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean at tincidunt sem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante.

#
# Features
#
features:

# Feature
- title: Clean & Unique Design
  description: Maecenas sed laoreet urna. Praesent eget tristique tortor. Suspendisse consequat sed turpis in mattis.
  icon: pe-7s-vector

# Feature
- title: Professional Support
  description: Maecenas sed laoreet urna. Praesent eget tristique tortor. Suspendisse consequat sed turpis in mattis.
  icon: pe-7s-help2

# Feature
- title: Pixel Perfect
  description: Maecenas sed laoreet urna. Praesent eget tristique tortor. Suspendisse consequat sed turpis in mattis.
  icon: pe-7s-airplay



#####################################
##########  Core Features  ##########
#####################################
core-title: Rum 1 - Fabrikant Johan Fagerlind
core-description: Det är den 19e mars,1924, och den fruktansvärda nyheten att Johan Fagerlind nyligen omkommit i en brand i sin skofabrik har nått hans tidigare kollega grosshandlare C.A. Carlsson. Fagerlind var skyldig Carlsson stora summor pengar och därför har grosshandlaren nu anställt er för att bryta er in i Johan Fagerlinds kontor och där leta upp hans kassaskåp och tömma det. Men skynda er på för stadens konstapel är också på väg dit och blir ni gripna är utebliven betalning för jobbet ert minsta problem.

core-title-2: Rum 2 - Major Cederströms vinkällare.
core-description-2: Spionage för Sovjetunionen. I3 örebro Livregementets grenadjärer. Första världskriget 1914 – 1918. Året är 1917 och Europa står i lågor medan världskriget rasar på. <br> <br><br><br>Kommer snart...



# #
# # Core Features Left
# #
# core-features-left:

# # Feature
# - name: Creative
#   description: Lorem ipsum dolor sit amet, consectetuer adipiscing diam.
#   icon: pe-7s-light

# # Feature
# - name: Minimalism
#   description: Lorem ipsum dolor sit amet, consectetuer adipiscing diam.
#   icon: pe-7s-drop

# # Feature
# - name: Clean Coding
#   description: Lorem ipsum dolor sit amet, consectetuer adipiscing diam.
#   icon: pe-7s-coffee

# # Feature
# - name: Friendly
#   description: Lorem ipsum dolor sit amet, consectetuer adipiscing diam.
#   icon: pe-7s-smile

# #
# # Core Features Right
# #
# core-features-right:

# # Feature
# - name: Branding
#   description: Lorem ipsum dolor sit amet, consectetuer adipiscing diam.
#   icon: pe-7s-wine

# # Feature
# - name: Web Design
#   description: Lorem ipsum dolor sit amet, consectetuer adipiscing diam.
#   icon: pe-7s-monitor

# # Feature
# - name: Graphic Design
#   description: Lorem ipsum dolor sit amet, consectetuer adipiscing diam.
#   icon: pe-7s-crop

# # Feature
# - name: Photography
#   description: Lorem ipsum dolor sit amet, consectetuer adipiscing diam.
#   icon: pe-7s-camera


#####################################
########### Testimonials ############
#####################################
testimonials-title: Testimonials
testimonials-description: Aenean at tincidunt sem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed, suscipit et nisi.

#
# Testimonials
#
testimonials:

# Client
- name: Johnatan Doe
  url: http://themeforest.net
  url-text: ThemeForest.net
  avatar: avatar-01.jpg
  cite: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer varius adipiscing lectus, eu ornare lectus semper in. Aenean at tincidunt sem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed.
  logo-img: themeforest.png

# Client
- name: Adam Smith
  url: http://codecanyon.net
  url-text: CodeCanyon.net
  avatar: avatar-02.jpg
  cite: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer varius adipiscing lectus, eu ornare lectus semper in. Aenean at tincidunt sem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed.
  logo-img: codecanyon.png

# Client
- name: Irene Warner
  url: http://videohive.net
  url-text: VideoHive.net
  avatar: avatar-03.jpg
  cite: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer varius adipiscing lectus, eu ornare lectus semper in. Aenean at tincidunt sem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed.
  logo-img: videohive.png

# Client
- name: Richard Ryan
  url: http://audiojungle.net
  url-text: AudioJungle.net
  avatar: avatar-04.jpg
  cite: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer varius adipiscing lectus, eu ornare lectus semper in. Aenean at tincidunt sem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed.
  logo-img: audiojungle.png


#####################################
############# Our Blog ##############
#####################################
blog-title: Our Blog
blog-description: Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed, suscipit et nisi. Nulla a tellus at turpis gravida congue non sed nisl. Pellentesque scelerisque eu neque et tincidunt.


#####################################
############### Team ################
#####################################
team-title: Meet Our Team
team-description: Nulla a tellus at turpis gravida congue non interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed, suscipit et nisi. Nulla a tellus at turpis gravida congue non sed nisl. Pellentesque scelerisque eu neque et tincidunt.

#
# Team Members
#
team:

# Team Member
- name: Jack Skilton
  tagline: Graphic Designer
  avatar: avatar-01.jpg

  # Social Links
  youtube: '#'
  pinterest: '#'
  facebook: '#'
  twitter: '#'
  google-plus: '#'
  vimeo: '#'

# Team Member
- name: James Young
  tagline: Developer
  avatar: avatar-02.jpg

  # Social Links
  youtube: '#'
  pinterest: '#'
  facebook: '#'
  twitter: '#'
  google-plus: '#'
  vimeo: '#'

# Team Member
- name: Johnatan Doe
  tagline: Hacker
  avatar: avatar-04.jpg

  # Social Links
  youtube: '#'
  pinterest: '#'
  facebook: '#'
  twitter: '#'
  google-plus: '#'
  vimeo: '#'

# Team Member
- name: Ecaterina Doe
  tagline: Support Expert
  avatar: avatar-03.jpg

  # Social Links
  youtube: '#'
  pinterest: '#'
  facebook: '#'
  twitter: '#'
  google-plus: '#'
  vimeo: '#'


#####################################
########## Pricing Tables ###########
#####################################
pricing-title: Pricing Tables
pricing-description: Nulla a tellus at turpis gravida congue non interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed, suscipit et nisi. Nulla a tellus at turpis gravida congue non sed nisl. Pellentesque scelerisque eu neque et tincidunt.

#
# Plan Personal
#
plan-personal-price: $99
plan-personal-offer-1-title: 01 PSD Pack
plan-personal-offer-1-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
plan-personal-offer-2-title: 100 Support Tickets
plan-personal-offer-2-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
plan-personal-url: '#'

#
# Plan Business
#
plan-business-price: $499
plan-business-offer-1-title: 05 PSD Pack
plan-business-offer-1-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
plan-business-offer-2-title: 1000 Support Tickets
plan-business-offer-2-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
plan-business-url: '#'

#
# Plan Ultimate
#
plan-ultimate-price: $999
plan-ultimate-offer-1-title: 10 PSD Pack
plan-ultimate-offer-1-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
plan-ultimate-offer-2-title: Support Unlimited
plan-ultimate-offer-2-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
plan-ultimate-url: '#'


#####################################
############   Contact   ############
#####################################
contact-title: Bokning
# contact-description: 

#####################################
#############   Footer   ############
#####################################
footer-description: Escape room är en del av Joche Inc.
footer-copyright-text: Joche
footer-copyright-url: http://daniel.sunden.se
footer-copyright-year: 2017
